name: release
on:
  - push
#  schedule:
#     - cron: '0 0 * * SAT' # every Saturday

jobs:
  build:
     runs-on: ubuntu-latest

     env:
       OPAMJOBS: 2
       OPAMRETRES: 8
       VERSION: 2.2.0

     steps:
         - name: Checkout code
           uses: actions/checkout@v2
           with:
             submodules: recursive

         - name: Install OCaml
           uses: avsm/setup-ocaml@v1
           with:
             ocaml-version: 4.09.1+flambda

         - name: Build deb packages
           run: ./tools/deb-build.sh ${{ env.VERSION }}

           # caution: this action overwrite the tag and deletes
           # releases that are associated with it
         - name: Create a new prerelease
           uses: "marvinpinto/action-automatic-releases@latest"
           with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: dev
             prerelease: true
             title: "Development Build"
             files: bap/*
